###############################################################################
#  In settings.py:
#       DATABASES = {
#            'default': {
#                'ENGINE': 'django.db.backends.mysql',
#                'HOST': 'mysql',
#                ...
#            }
#        }
#
#  In PyCharm configurations:
#       Host: 0.0.0.0 - Port: 8000
#       Python interpreter: Select the docker ...
###############################################################################
version: "3.1"

volumes:
    db-data:

services:

    django:
      build: ./docker/django
      container_name: ${PROJECT_NAME}-django
      command: python3 manage.py runserver 0.0.0.0:8000
      restart: always
      volumes:
        - .:/application
      ports:
        - "127.0.0.1:8000:8000"
      depends_on:
        - db
      restart: on-failure  

    db:
      image: mariadb:10.4
      container_name: ${PROJECT_NAME}-database
      working_dir: /application
      restart: always
      volumes:
        - db-data:/application
      environment:
        - MYSQL_ROOT_PASSWORD=docker_root
        - MYSQL_DATABASE=plants_project_db
        - MYSQL_USER=api_user
        - MYSQL_PASSWORD=GBSy933mKVx3SY2j&V
      expose:
        - "3306"

    pma:
      image: phpmyadmin/phpmyadmin
      container_name: ${PROJECT_NAME}-pma
      restart: always
      links:
        - db:db
      ports:
        - "127.0.0.1:8080:80"
      environment:
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: docker_root
        PMA_ABSOLUTE_URI: "https://plants.ml/pma/"
